--[[
	Fury - English Localization
	Extended by: Cubenicke
	By: Bhaerau
]]--

BINDING_NAME_FURY			= "Attack";
BINDING_NAME_FURY_AOE			= "Toggle AoE";
BINDING_NAME_FURY_WW			= "Toggle Whirlwind";
BINDING_NAME_FURY_THREAT		= "Toggle HS or Cleave";
BINDING_NAME_FURY_DW			= "Toggle Death Wish";
BINDING_HEADER_FURY			= "Fury";
BINDING_NAME_FURY_CHARGE		= "Charge";
BINDING_NAME_FURY_BLOCK			= "Block";

CLASS_DRUID_FURY			= "Druid";
CLASS_HUNTER_FURY			= "Hunter";
CLASS_MAGE_FURY				= "Mage";
CLASS_PALADIN_FURY			= "Paladin";
CLASS_PRIEST_FURY			= "Priest";
CLASS_ROGUE_FURY			= "Rogue";
CLASS_SHAMAN_FURY			= "Shaman";
CLASS_WARLOCK_FURY			= "Warlock";
CLASS_WARRIOR_FURY			= "Warrior";

RACE_ORC				= "Orc";
RACE_TROLL				= "Troll";
RACE_DWARF				= "Dwarf";

ABILITY_BATTLE_SHOUT_FURY		= "Battle Shout";
ABILITY_BATTLE_STANCE_FURY		= "Battle Stance";
ABILITY_BERSERKER_RAGE_FURY		= "Berserker Rage";
ABILITY_BERSERKER_STANCE_FURY		= "Berserker Stance";
ABILITY_BLOODRAGE_FURY			= "Bloodrage";
ABILITY_BLOODTHIRST_FURY		= "Bloodthirst";
--ABILITY_CHALLENGING_SHOUT_FURY	= "Challenging Shout";
ABILITY_CHARGE_FURY			= "Charge";
ABILITY_CLEAVE_FURY			= "Cleave";
--ABILITY_CONCUSSION_BLOW_FURY		= "Concussion Blow";
ABILITY_DEATH_WISH_FURY			= "Death Wish";
ABILITY_BLOOD_FURY			= "Blood Fury";
ABILITY_DEFENSIVE_STANCE_FURY		= "Defensive Stance";
ABILITY_DEMORALIZING_SHOUT_FURY		= "Demoralizing Shout";
ABILITY_DISARM_FURY			= "Disarm";
ABILITY_EXECUTE_FURY			= "Execute";
ABILITY_HAMSTRING_FURY			= "Hamstring";
ABILITY_HEROIC_STRIKE_FURY		= "Heroic Strike";
ABILITY_INTERCEPT_FURY			= "Intercept";
--ABILITY_INTIMIDATING_SHOUT_FURY	= "Intimidating Shout";
--ABILITY_LAST_STAND_FURY		= "Last Stand";
--ABILITY_MOCKING_BLOW_FURY		= "Mocking Blow";
ABILITY_MORTAL_STRIKE_FURY		= "Mortal Strike";
ABILITY_OVERPOWER_FURY			= "Overpower";
ABILITY_PIERCING_HOWL_FURY		= "Piercing Howl";
ABILITY_PUMMEL_FURY			= "Pummel";
--ABILITY_RECKLESSNESS_FURY		= "Recklessness";
ABILITY_REND_FURY			= "Rend";
--ABILITY_RETALIATION_FURY		= "Retaliation";
ABILITY_REVENGE_FURY			= "Revenge";
ABILITY_SHIELD_BASH_FURY		= "Shield Bash";
ABILITY_SHIELD_BLOCK_FURY		= "Shield Block";
ABILITY_SHIELD_SLAM_FURY		= "Shield Slam";
--ABILITY_SHIELD_WALL_FURY		= "Shield Wall";
--ABILITY_SLAM_FURY			= "Slam";
ABILITY_SHOOT_BOW_FURY			= "Shoot Bow";
ABILITY_SHOOT_CROSSBOW_FURY		= "Shoot Crossbow";
ABILITY_SHOOT_GUN_FURY			= "Shoot Gun";
ABILITY_STONEFORM_FURY			= "Stoneform";
--ABILITY_SUNDER_ARMOR_FURY		= "Sunder Armor";
ABILITY_SWEEPING_STRIKES_FURY		= "Sweeping Strikes";
--ABILITY_TAUNT_FURY			= "Taunt";
ABILITY_THUNDER_CLAP_FURY		= "Thunder Clap";
ABILITY_THROW_FURY			= "Throw";
ABILITY_WHIRLWIND_FURY			= "Whirlwind";

RACIAL_BERSERKING_FURY			= "Berserking";

CHAT_OVERPOWER1_FURY			= "You attack.(.+) dodges.";
CHAT_OVERPOWER2_FURY			= "Your (.+) was dodged by (.+).";
CHAT_OVERPOWER3_FURY			= "Your Overpower crits (.+) for (%d+)."
CHAT_OVERPOWER4_FURY			= "Your Overpower hits (.+) for (%d+)."
CHAT_OVERPOWER5_FURY			= "Your Overpower missed (.+)."
CHAT_RUNNER_FURY			= "%s attempts to run away in fear!"
CHAT_CAST_FURY				= "(.+) begins to cast (.+).";
CHAT_INTERRUPT1_FURY			= "You interrupt (.+).";
CHAT_INTERRUPT2_FURY			= "Your Pummel was (.+) by (.+).";
CHAT_INTERRUPT3_FURY			= "Your Shield Bash was (.+) by (.+).";
CHAT_INTERRUPT4_FURY			= "Your Pummel missed (.+).";
CHAT_INTERRUPT5_FURY			= "Your Shield Bash missed (.+).";
CHAT_WHIRLWIND_FURY			= "Your Whirlwind (.+).";
CHAT_CLEAVE_FURY			= "Your Cleave (.+).";

CHAT_DODGE_FURY				= "You dodge";
CHAT_PARRY_FURY				= "You parry";
CHAT_BLOCK_FURY				= "You block";

CHAT_FEAR_FURY				= "You are afflicted by Fear.";
CHAT_INTIMIDATING_SHOUT_FURY		= "You are afflicted by Intimidating Shout.";
CHAT_PSYCHIC_SCREAM_FURY		= "You are afflicted by Psychic Scream.";
CHAT_PANIC_FURY				= "You are afflicted by Panic.";
CHAT_BELLOWING_ROAR_FURY		= "You are afflicted by Bellowing Roar.";
CHAT_ANCIENT_DESPAIR_FURY		= "You are afflicted by Ancient Despair.";
CHAT_TERRIFYING_SCREECH_FURY		= "You are afflicted by Terrifying Screech.";
CHAT_HOWL_OF_TERROR_FURY		= "You are afflicted by Howl of Terror.";
CHAT_SAP_FURY				= "You are afflicted by Sap.";
CHAT_GOUGE_FURY				= "You are afflicted by Gouge.";
CHAT_REPENTANCE_FURY			= "You are afflicted by Repentance.";
CHAT_ROCKET_HELM_FURY			= "You are afflicted by Reckless Charge.";

CHAT_FEAR2_FURY				= "Fear fades from you.";
CHAT_INTIMIDATING_SHOUT2_FURY		= "Intimidating Shout fades from you.";
CHAT_PSYCHIC_SCREAM2_FURY		= "Psychic Scream fades from you.";
CHAT_PANIC2_FURY			= "Panic fades from you.";
CHAT_BELLOWING_ROAR2_FURY		= "Bellowing Roar fades from you.";
CHAT_ANCIENT_DESPAIR2_FURY		= "Ancient Despair fades from you.";
CHAT_TERRIFYING_SCREECH2_FURY		= "Terrifying Screech fades from you.";
CHAT_HOWL_OF_TERROR2_FURY		= "Howl of Terror fades from you.";
CHAT_SAP2_FURY				= "Sap fades from you.";
CHAT_GOUGE2_FURY			= "Gouge fades from you.";
CHAT_REPENTANCE2_FURY			= "Repentance fades from you.";
CHAT_ROCKET_HELM2_FURY			= "Reckless Charge fades from you.";
CHAT_IS_ON_CD_FURY			= "is on CD, replace?";
CHAT_MISSING_SPELL_SHOOT_THROW_FURY	= "Missing spell on action bar Shoot or Throw";
CHAT_MISSING_SPELL_INTERCEPT_CHARGE_FURY	= "Missing spell on action bar Intercept or Charge";
CHAT_MISSING_SPELL_THUNDERCLAP_FURY	= "Missing spell on action bar Thunder Clap";
CHAT_MISSING_SPELL_PUMMEL_FURY		= "Missing spell on action bar (any close combat spell, like Pummel)";
CHAT_DISARM_IMMUNE_FURY			= "Your Disarm failed. (.+) is immune.";

CHAT_DISABLING_AOE_FURY			= "Disabling AoE";
CHAT_BUFFS_FURY				= "Buffs:";
CHAT_DEBUFFS_FURY			= "Debuffs:";
CHAT_KICKED_FURY			= "Kicked";
CHAT_TALENTS_RESCAN_FURY		= "Rescanning talent tree and actionbars";

ITEM_GAUNTLETS1_FURY			= "Knight-Lieutenant's Plate Gauntlets";
ITEM_GAUNTLETS2_FURY			= "Marshal's Plate Gauntlets";
ITEM_GAUNTLETS3_FURY			= "Blood Guard's Plate Gloves";
ITEM_GAUNTLETS4_FURY			= "General's Plate Gauntlets";
ITEM_TRINKET_INSIGNIA_OF_THE_ALLIANCE_FURY = "Insignia of the Alliance";
ITEM_TRINKET_INSIGNIA_OF_THE_HORDE_FURY	= "Insignia of the Horde"
ITEM_TRINKET_LINKENS_BOOMERANG_FURY	= "Linken's Boomerang";
ITEM_TRINKET_TIDAL_CHARM		= "Tidal Charm";
ITEM_TRINKET_EARTHSTRIKE		= "Earthstrike";
ITEM_TRINKET_KOTS			= "Kiss of the Spider";
ITEM_TRINKET_SLAYERS_CREST		= "Slayer's Crest";
ITEM_TRINKET_HEART_OF_NOXXION		= "Heart of Noxxion";
ITEM_BELT_SPIDER_BELT_FURY		= "Spider Belt";
ITEM_BOOTS_ORNATE_MITHRIL_BOOTS_FURY	= "Ornate Mithril Boots";

ITEM_TYPE_SHIELDS_FURY			= "Shields";
ITEM_TYPE_BOWS_FURY			= "Bows";
ITEM_TYPE_CROSSBOWS_FURY		= "Crossbows";
ITEM_TYPE_GUNS_FURY			= "Guns";
ITEM_TYPE_THROWN_FURY			= "Thrown";

ITEM_DEBUFF_TYPE_POISON			= "Poison";
ITEM_DEBUFF_TYPE_DISEASE		= "Disease";
ITEM_DEBUFF_TYPE_CURSE			= "Curse";
ITEM_DEBUFF_TYPE_MAGIC			= "Magic";

ITEM_CONS_JUJU_FLURRY			= "Juju Flurry";
ITEM_CONS_JUJU_POWER			= "Juju Power";
ITEM_CONS_JUJU_MIGHT			= "Juju Might";
ITEM_CONS_JUJU_EMBER			= "Juju Ember";
ITEM_CONS_JUJU_CHILL			= "Juju Chill";
ITEM_CONS_OIL_OF_IMMOLATION		= "Oil of Immolation";
ITEM_CONS_JUNGLE_REMEDY			= "Jungle Remedy";
ITEM_CONS_POWERFUL_ANTIVENOM		= "Powerful Anti-Venom";
ITEM_CONS_ELIXIR_OF_POISION_RESISTANCE	= "Elixir of Poison Resistance";
ITEM_CONS_PURIFICATION_POTION		= "Purification Potion";

BOSS_NAX_GOTHIK_THE_HARVESTER_FURY	= "Gothik the Harvester";
BOSS_NAX_GRAND_WIDOW_FAERLINA_FURY	= "Grand Widow Faerlina";
BOSS_NAX_HEIGAN_THE_UNCLEAN_FURY	= "Heigan the Unclean";
BOSS_NAX_KEL_THUZAD_FURY		= "Kel'Thuzad";
BOSS_NAX_LADY_BLAUMEUX_FURY		= "Lady Blaumeux";
BOSS_NAX_LOATHEB_FURY			= "Loatheb";
BOSS_NAX_SAPPHIRON_FURY			= "Sapphiron";
BOSS_NAX_SIR_ZELIEK_FURY		= "Sir Zeliek";
BOSS_NAX_THANE_KORTH_AZZ_FURY		= "Thane Korth'azz";
BOSS_AQ40_EMPEROR_VEK_LOR_FURY		= "Emperor Vek'lor";
BOSS_AQ40_PRINCE_HUHURAN_FURY		= "Princess Huhuran";
BOSS_AQ40_THE_PROPHET_SKERAM_FURY	= "The Prophet Skeram";
BOSS_MC_MAGMADAR_FURY			= "Magmadar";
BOXX_MC_RAGNAROS_FURY			= "Ragnaros";
BOSS_MC_SHAZZRATH_FURY			= "Shazzrath";
BOSS_ONYXIA_FURY			= "Onyxia";
BOSS_STRAT_BARON_RIVENDERE_FURY		= "Baron Rivendare";

MODE_HEADER_AOE				= "AoE";
MODE_HEADER_DEBUFF			= "Debuff";
SLASH_FURY_ENABLED			= "enabled";
SLASH_FURY_DISABLED			= "disabled";
SLASH_FURY_DEFAULT			= "default";
SLASH_FURY_DEBUG			= "Debug";
SLASH_FURY_DISTANCE			= "Distance";
SLASH_FURY_YARDS			= "yards";
SLASH_FURY_NO_ATTACKABLE_TARGET		= "You need to have an attackable target";
SLASH_FURY_NOT_FOUND			= "not found";
SLASH_FURY_DEMODIFF			= "Max target difference in levels for using Demoralizing Shout is set to ";
SLASH_FURY_AUTOATTACK			= "Autoattack";
SLASH_FURY_ATTACKRAGE			= "Attackrage";
SLASH_FURY_VERSION			= "Version";
SLASH_FURY_DANCE			= "Rage allowed to be wasted when switching stance set to ";
SLASH_FURY_RAGE				= "Maximum rage allowed when using abilities to gain rage set to ";
SLASH_FURY_RAGE				= "Minimum rage required when using Heroic Strike or Cleave set to ";
SLASH_FURY_BLOODRAGE			= "Minimum percent of health required when using Bloodrage set to ";
SLASH_FURY_DEATHWISH			= "Minimum percent of health required when using Death Wish set to ";
SLASH_FURY_HAMSTRING			= "Maximum percent of health allowed when using Hamstring on NPCs set to ";
SLASH_FURY_LOWTHREAT			= "Low threat enabled, enabled Cleave.";
SLASH_FURY_HIGHTHREAT			= "High threat enabled, enabled Heroic Strike.";
SLASH_FURY_TROLL			= "Maximum percent of health allowed when using Berserking set to ";
SLASH_FURY_STANCE			= "Primary stance set to ";
SLASH_FURY_NOSTANCE			= "Stance switching ";
SLASH_FURY_HELP				= "use /fury help <cmd> to get more help, commands are: ";
HELP_AOE				= "/fury aoe - disables bloodthirst/mortal strike and enables Cleave";
HELP_ATTACK				= "/fury attack - toggles the use of autoattack. Experimental.";
HELP_ATTACKRAGE				= "/fury attackrage <number> - sets minimum rage required when using Heroic Strike or Cleave";
HELP_ABILITY				= "/fury ability <name> - toggles the use of abilities. Must use correct names with capitalization, ie. Heroic Strike, Rend etc.";
HELP_BERSERK				= "/fury berserk <number> - sets minimum percent of health required when using Berserk";
HELP_BLOCK				= "/fury block - Shifts to defensive and activates block";
HELP_BLOODRAGE				= "/fury bloodrage <number> - sets minimum percent of health required when using Bloodrage";
HELP_CHARGE				= "/fury charge - will use charge or intercept sequence"
HELP_DANCE				= "/fury dance <number> - sets rage allowed to be wasted when switching stance (dancing)";
HELP_DEBUFF				= "/fury debuff - toggles use of debuff spells/cons";
HELP_DEBUG				= "/fury debug - writes commands in log";
HELP_DEMODIFF				= "/fury demodiff <number> - sets maximum level differrence to use Demoralizing Shout";
HELP_DISTANCE				= "/fury distance - Gives distance to target";
HELP_EARTHSTRIKE			= "/fury Earthstrike -- toggles use of trinket on every cooldown"
HELP_HAMSTRING				= "/fury hamstring <number> - sets maximum percent of health allowed when using Hamstring on NPCs";
HELP_HELP				= "/fury help - outputs available commands";
HELP_JUJU				= "/fury juju <juju> - Supports flurry, power, might, chill and ember toggles use of the <juju> on cooldown";
HELP_KOTS				= "/fury kots - toggles use of trinket on every cooldown";
HELP_LOG				= "/fury log [on|off] - Create a channel and log to <wow>\\Logs\\WowChatLog.txt";
HELP_OOI				= "/fury ooi - toggle use of Oil of Immolation";
HELP_RAGE				= "/fury rage <number> - sets maximum rage allowed when using abilities to gain rage";
HELP_SHOOT				= "/fury shoot - Fires equipped ranged weapon";
HELP_SLAYERS_CREST			= "/fury Slayer's Crest - toggle use of Slayer's Crest";
HELP_STANCE				= "/fury stance <1|2|3|name> - sets stance to return to after switching stance. If default is selected it will return to your last used stance. If no stance is selected it will disable stance switching. (Must use correct names with capitalization.)";
HELP_TALENTS				= "/fury talents - Rescan spells and talents (needed after movement in action bar)";
HELP_THREAT				= "/fury threat - enables Cleave or Heroic Strike based on current settings";
HELP_TOGGLE				= "/fury toggle - toggle if addon is active";
HELP_UNIT				= "/fury unit - debug info";
HELP_UNKNOWN				= "Unknown command /fury help - for list of commands";HELP_WHERE				= "/fury where - debug info";
